version: "3"
services:
  gpconnect-db:
    image: mariadb
    networks: 
      - gpconnect-network-1.5
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=gpconnectdbuser
      - MYSQL_PASSWORD=gpc0nn3ct
      - MYSQL_DATABASE=gpconnect1_5
  gpconnect-api:
    image: gpconnect # rename to whatever you tagged the GP Connect build is
    ports:
      - 9000:19191
      - 9001:19192
    networks: 
      - gpconnect-network-1.5
    environment:
      - DATABASE_ADDRESS=gpconnect-db
      - DATABASE_USERNAME=gpconnectdbuser
      - DATABASE_PASSWORD=gpc0nn3ct
      - DATABASE_SCHEMA=gpconnect1_5
      - SERVER_BASE_URL=https://data.developer.nhs.uk/B82617/STU3/1/gpconnect/fhir
      - CONTEXT_PATH=/B82617/STU3/1/gpconnect/
    links:
      - gpconnect-db
    depends_on:
      - gpconnect-db

networks: 
  gpconnect-network-1.5:
    driver: bridge
